# Generated by Django 3.1.2 on 2020-10-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack_type',
            name='attack_type',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
