# Generated by Django 3.1.2 on 2020-10-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('author', models.CharField(blank=True, max_length=100)),
                ('target', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('records_lost', models.PositiveIntegerField(blank=True)),
                ('monetary_cost', models.PositiveIntegerField(blank=True)),
                ('link1', models.CharField(max_length=300)),
                ('link2', models.CharField(blank=True, max_length=300)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('vetted', models.BooleanField(default=False)),
            ],
        ),
    ]
