# Generated by Django 3.1.2 on 2020-10-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('target', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(max_length=500)),
                ('records_lost', models.PositiveIntegerField(blank=True, null=True)),
                ('monetary_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('link1', models.CharField(max_length=300)),
                ('link2', models.CharField(blank=True, max_length=300, null=True)),
                ('tag', models.CharField(blank=True, max_length=200, null=True)),
                ('vetted', models.BooleanField(default=False)),
                ('attack_classes', models.ManyToManyField(blank=True, related_name='attack_class_selection', to='classification.Attack_Class')),
                ('attack_types', models.ManyToManyField(blank=True, related_name='attack_type_selection', to='classification.Attack_Type')),
                ('countries', models.ManyToManyField(blank=True, related_name='country_list', to='classification.Country')),
            ],
        ),
    ]
