# Generated by Django 3.1.2 on 2020-10-22 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classification', '0002_auto_20201022_1532'),
        ('incident', '0002_auto_20201021_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='attack_classes',
            field=models.ManyToManyField(related_name='attack_class_selection', to='classification.Attack_Class'),
        ),
        migrations.AddField(
            model_name='incident',
            name='attack_types',
            field=models.ManyToManyField(related_name='attack_type_selection', to='classification.Attack_Type'),
        ),
        migrations.AddField(
            model_name='incident',
            name='countries',
            field=models.ManyToManyField(related_name='country_list', to='classification.Country'),
        ),
        migrations.AddField(
            model_name='incident',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filed_incident', to='jwt_auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='target_classes',
            field=models.ManyToManyField(related_name='target_type_selection', to='classification.Target_Class'),
        ),
    ]
