# Generated by Django 3.1.2 on 2020-10-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20201022_1532'),
        ('incident', '0004_auto_20201022_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='attack_classes',
            field=models.ManyToManyField(blank=True, related_name='attack_class_selection', to='classification.Attack_Class'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='attack_types',
            field=models.ManyToManyField(blank=True, related_name='attack_type_selection', to='classification.Attack_Type'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='country_list', to='classification.Country'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='target_classes',
            field=models.ManyToManyField(blank=True, related_name='target_type_selection', to='classification.Target_Class'),
        ),
    ]
